# Generated by Django 4.1.6 on 2023-02-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu_ID', models.CharField(max_length=20)),
                ('Stu_Name', models.CharField(max_length=10)),
                ('Stu_Gender', models.CharField(max_length=5)),
                ('Stu_Age', models.IntegerField()),
                ('Stu_College', models.CharField(max_length=40)),
                ('Stu_Username', models.CharField(max_length=50)),
                ('Stu_Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tch_ID', models.CharField(max_length=20)),
                ('Tch_Name', models.CharField(max_length=10)),
                ('Tch_College', models.CharField(max_length=40)),
                ('Tch_Position', models.CharField(max_length=5)),
                ('Tch_Username', models.CharField(max_length=50)),
                ('Tch_Password', models.CharField(max_length=50)),
            ],
        ),
    ]
