# Generated by Django 4.1.7 on 2023-02-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tchinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='Stu_ID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tchinfo',
            name='Tch_ID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
