# Generated by Django 4.1.7 on 2023-02-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSys', '0002_remove_stuinfo_id_remove_tchinfo_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('Crs_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Crs_Name', models.CharField(max_length=10)),
                ('Crs_Credit', models.IntegerField()),
                ('Crs_Period', models.IntegerField()),
                ('Crs_CollegeNum', models.IntegerField()),
            ],
        ),
    ]
