# Generated by Django 4.1.7 on 2023-02-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSys', '0003_courseinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartInfo',
            fields=[
                ('Dep_ID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Dep_Name', models.CharField(max_length=20)),
                ('Dep_Addr', models.CharField(max_length=40)),
                ('Dep_PhoneNum', models.CharField(max_length=11)),
            ],
        ),
        migrations.DeleteModel(
            name='CourseInfo',
        ),
        migrations.DeleteModel(
            name='StuInfo',
        ),
        migrations.DeleteModel(
            name='TchInfo',
        ),
    ]
