# Generated by Django 4.1.7 on 2023-02-15 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSys', '0004_departinfo_delete_courseinfo_delete_stuinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TchInfo',
            fields=[
                ('Tch_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Tch_Name', models.CharField(max_length=10)),
                ('Tch_Position', models.CharField(max_length=5)),
                ('Tch_Username', models.CharField(max_length=50)),
                ('Tch_Password', models.CharField(max_length=50)),
                ('Tch_Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSys.departinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('Stu_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Stu_Name', models.CharField(max_length=10)),
                ('Stu_Gender', models.CharField(max_length=5)),
                ('Stu_Age', models.IntegerField()),
                ('Stu_Username', models.CharField(max_length=50)),
                ('Stu_Password', models.CharField(max_length=50)),
                ('Stu_Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSys.departinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('Crs_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Crs_Name', models.CharField(max_length=10)),
                ('Crs_Credit', models.IntegerField()),
                ('Crs_DepartNum', models.IntegerField()),
                ('Crs_Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentSys.departinfo')),
            ],
        ),
    ]
