# Generated by Django 4.1.7 on 2023-02-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSys', '0005_tchinfo_stuinfo_courseinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinfo',
            old_name='Crs_DepartNum',
            new_name='Crs_Period',
        ),
    ]
