# Generated by Django 4.1.7 on 2023-02-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSys', '0006_rename_crs_departnum_courseinfo_crs_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tchinfo',
            name='Tch_Position',
            field=models.CharField(max_length=10),
        ),
    ]
