# Generated by Django 4.1.7 on 2023-02-16 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSys', '0007_alter_tchinfo_tch_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OCrs_Term', models.CharField(max_length=20)),
                ('Ocrs_ClassTime', models.CharField(max_length=50)),
                ('OCrs_Course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='StudentSys.courseinfo')),
                ('OCrs_Teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='StudentSys.tchinfo')),
            ],
        ),
    ]
