# Generated by Django 4.1.7 on 2023-02-16 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSys', '0008_offeredcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SelCrs_Course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='StudentSys.offeredcourse')),
                ('SelCrs_Stu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='StudentSys.stuinfo')),
            ],
        ),
    ]
