# Generated by Django 4.1.7 on 2023-02-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSys', '0009_selectcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectcourse',
            name='SelCrs_Grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
